---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-telegram-secret
  namespace: n8n
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBm5yask76M5LZRXCmLWkC/fzO45KD94oeXjWSpDHKtcMMCY/YeXZR675Tgx2l3vYpNuVNilIdRhRAVBuTMsuMZY+oVJMGiUsIR71vyfH4Q6YQbp427zZX7egEDRaNfeIKgpTNDcK3vgzUzVuvzM1O4bjjkViKrTF6gGqFa6CpPVzMJnHkNQXR3uDGnUoxX7FacsNljUyGomnFBtDSTy9092BoOa4GuvEN43pbHs8mfE1kV8ylG4l03IR4ePvj83JkXOX4tklgog1PjQAOwCmbEyeqcOgiq1ui4gptZtDJtSIqvcOfL2Ue+jrt3r57JmASfNF+u8fBgEa4XAM0jiKOdkeRF/7ejQ/qIDleznXFAiTrutrUNDlx5CtbaKvST4dRrOBbYhcHG+ofpbZe6kJ4hob00qSwJe4JlEGjo1DQNt0yDoFTeKWMs9zfJhfEe7l4LPVqFYWRC5aJcnnPq5cr4nWetnosHBToAk6EqCgshzpDpyrWktweA71mKfFZRwn1QDWGvHff5ZZsolaRTaDFHieSCymwUWZfQOyUu/c1Q/WC64E614dfEu0Lr2vGPGWLrqvTy4/BWzZbVWWZtx59h2s9RXrcOHK2V8JI9bRRL9lus2LP9rBxagsf7TEqPgPNj2RglGXfcfxsC6D4Y5MjBhdUlKesbNbyBXl5sRVVMMvZlPKw/cu003eL/WumA7wN+fo5YcJ+Nwrc3FoD3S5zMv0oPxb3mkP+MoVUINqj0N3i9YWp1x4BpwMtp5c+l
  template:
    metadata:
      name: n8n-telegram-secret
      namespace: n8n
