apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: http
      path: /minio/v2/metrics/cluster
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      app: minio
      release: minio
      monitoring: "true"
