apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single   # 1 replica — will schedule on worker-02 (has 32GB free)
  resources:
    requests:
      storage: 5Gi
