apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shevchenkod/devops-lab.git
    targetRevision: HEAD
    path: apps/strapi
  destination:
    server: https://kubernetes.default.svc
    namespace: strapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
