apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi
  namespace: strapi
  annotations:
    cert-manager.io/cluster-issuer: lab-ca-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - strapi.lab.local
      secretName: strapi-tls
  rules:
    - host: strapi.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi
                port:
                  number: 1337
