apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
  namespace: strapi
type: Opaque
data:
  # ⚠️ Lab only — in prod use SealedSecrets / ExternalSecrets
  # Generated: 01.01.2026
  app_keys: UWhMVWZhd0YyUGdpYTlnTU1TSFQ1TnZCWTkwTVVHeHVrby9pOElCY0hkMD0sdmhWeFdXbitYNHZHaFdpVVdiL24wUnV5bmtlS0FIbklLL3NuekNVUWpudz0=
  api_token_salt: UUxKdWIzWkR0cndrU2o0SzVDZ2ZwUkJXdXU1OE1LK3dvZUxvUUhWaVNrOD0=
  admin_jwt_secret: RGZJcHpKYld6a2s1L0MzczR4YjI1RHQwWmFQSTM3cDlqNktIVTZEYnUwQT0=
  jwt_secret: M2NtYlNmL2E1N0VHbTVHOXQ3RUczOWEzTkh0YXJhRi9TNUdxK0lZY1pUYz0=
  transfer_token_salt: dHRJUGJOUmdacjZZK2diR1NXckltTzJGSjRGZmR0ckJzZFc3ZDNiZnlHbz0=
